#pragma once

#define CELL_SIZE 16
#define WINDOW_WIDTH_CELL 32
#define MAP_WIDTH_CELL 424
#define MAP_HEIGHT_CELL 30
#define WINDOW_WIDTH (WINDOW_WIDTH_CELL * CELL_SIZE)
#define WINDOW_HEIGHT (MAP_HEIGHT_CELL * CELL_SIZE)